before:
  hooks:
    - make install

builds:
  - binary: wtf
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64

env:
  - GO111MODULE=on
  - GOPROXY="https://gocenter.io"

archive:
  wrap_in_directory: true
