env:
  - GO111MODULE=on
  - GOPROXY="https://gocenter.io"

before:
  hooks:
    - make install

builds:
  - binary: wtfutil
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64

archive:
  wrap_in_directory: true
